OUTPUT:
  DIR: './out/'

SOLVER:
  CORR_TYPE: 'PEARSON'
  CROSS_VAL: False
  K_FOLDS: 8

FE:
  GAMMA: 1
  K: 4

DATASETS:
  TRAIN_TEST_SPLIT: 'dataset/lervup_data/train_test_split_mobinet_v1.json'
  GT_USER_EXPOS: 'dataset/lervup_data/gt_usr_exposure_v1.json'
  VIS_CONCEPTS: 'dataset/lervup_data/visual_concepts/'