MODEL:
  DEBUG: False
  PLOT: False

##
DETECTOR:
  LOAD: True

##
USER_SELECTOR:
  STATE: False
  EPS: 0.05
  KEEP: 1.0

##
SOLVER:
  F_TOP: 0.1
  PFT: 'POOLING'
  FEATURE_TYPE: 'ORG'
  CORR_TYPE: 'PEARSON'
  FILTERING: True
  FILT: 0.05

##
FE:
  GAMMA: 0
  K: 15
  TAU_e: 10.0
  TAU_o: 0.66
  TAU_i: 0.5 # only scale when image objectness is sufficiently high

##
PCA:
  STATE: False

##
DATASETS:
  TRAIN_TEST_SPLIT: "dataset/lervup_data/train_val_test_split_mobinet_v3.json"
  GT_USER_EXPOS: "dataset/lervup_data/gt_usr_exposure_v1.json"
  VIS_CONCEPTS: "dataset/lervup_data/visual_concepts/"
  PRE_VIS_CONCEPTS:  "base_algo/base_opt/out/mobi_optimal_thres_situs_v3_active.txt"

##
OUTPUT:
  VERBOSE: False